### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#106]
The current JavaScript modules are concatenated/compiled into the main file, more or less in an arbitrary order; only the subdirectory names of `/[e]xtensions` and `/[p]lugins` happen to produce the desired outcome due to alphabetical order :-)

@markcarver and I discussed this a little bit in IRC and we agreed that a proper dependency injection system is in order.  But unlike typical DI constructs (like AMD, requireJS), all sub-scripts will still be compiled into a main file, so a DI approach in _functional code_ is unnecessary.

Ideally, each individual file would specify its dependencies. — In an ideal DX world, grunt would automatically parse and extract the dependencies from a wrapping function closure even.

Mark quickly grepped the net and found the following two grunt plugins:
1. https://github.com/trek/grunt-neuter
2. https://github.com/leoselig/grunt-concat-deps

Neuter looks interesting, but it looks like stuff needs to be specified in Gruntfile.js instead of individual files.

grunt-concat-deps OTOH, leverages JSDoc annotations to declare `@module` names and their dependencies via `@requires`. → While not 100% optimal, that is certainly a 100% improvement compared to status quo.  We can still replace/remove that solution with a better one if we happen to find one later on.

**Comment by markhalliwell** [comment]
:+1:

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#37
