### ISSUE TITLE
Rename 1.x branch to master

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#114]
The `1.x` branch name is obsolete and can be renamed to the common `master` branch, since `2.x` is already `1.x` by now, and all development is going to be linear from now on.

I would have normally done this directly without issue, but I'm not sure whether there are any further dependencies on the current `1.x` branch name in (external) build scripts?

**Comment by markhalliwell** [comment]
Yes, dreditor.org has code that will need to be modified. There will need to be some Travis CI modification in this repo too.

Typos courtesy of Siri

**Comment by sun** [comment]
Thanks — #115 resolves at least all references to `1.x` in code.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#33
