### ISSUE TITLE
add a participant list button like create commit message button

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#116]
![createcommitmessage](https://cloud.githubusercontent.com/assets/1970586/2560857/0d4b6e04-b7e8-11e3-8a5f-0fdec59aa8c0.png)

related to https://drupal.org/node/1304558 "Provide a page showing all the users following a given issue"

![people](https://cloud.githubusercontent.com/assets/1970586/2560889/12ff5560-b7eb-11e3-9e95-d841585c33ba.png)

(heh. typo in there "most date") I think I meant just date (or most recent)

**Comment by YesCT** [comment]
Related d.o issue:
https://drupal.org/node/2231415 "Add a list of commenters' usernames to the issue page"

**Comment by iant-ee** [comment]
I've raised a separate issue to add this information to commit messages: https://drupal.org/node/2230579

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#32
