### ISSUE TITLE
Switch build:firefox from cfx to jpm (Jetpack)?

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#130]
Context: The [mozilla-addon-sdk](https://github.com/mozilla/addon-sdk)'s `activate.bat` fails to find the path to Python on Windows, if the Python install directory contains a space. — In looking into that bug ([789725](https://bugzilla.mozilla.org/show_bug.cgi?id=789725), [840819](https://bugzilla.mozilla.org/show_bug.cgi?id=840819)), I noticed a completely different issue in Mozilla's issue tracker:

[915376 - JEP Native Jetpack](https://bugzilla.mozilla.org/show_bug.cgi?id=915376)
mozilla/addon-sdk#1241

...which is apparently scheduled for Q2/2014 and announces [The Future of Cuddlefish](https://github.com/mozilla/addon-sdk/pull/1241/files?short_path=85dee71#the-future-of-cuddlefish):

> This will be the **end of life for our cuddlefish/cfx command line tool** (for reasons stated above) as a thing that is meant for community use, if it exists at all then it will be a small fragment of what it used to be.
> 
> The new tool is [jpm](https://github.com/mozilla/jpm).

Docs: [Mozilla Jetpack manual](https://wiki.mozilla.org/Jetpack)

The `activate[.bat]` script of the SDK is just a dumb wrapper to find the python executable and start the Jetpack SDK environment:

```
python -c "from jetpack_sdk_env import welcome; welcome()"
```

But given the above findings, I now wonder whether I need to spend any time to fix that bug in the SDK, in case there is a chance that we'll switch from `cfx` to `jpm` anytime soon?

I didn't try out jpm yet; still ramping up on more basic extension building aspects. - Thoughts?

**Comment by markhalliwell** [comment]
Just from looking at jpm, it's node.js based (which is what this project is)... which is freakin awesome :D So I think we should probably ditch cfx entirely once jpm comes out (officially, currently failing builds). I don't think we should waste time on trying to fix cfx at all now.

**Comment by star-szr** [comment]
#268

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#31
