### ISSUE TITLE
Git clone URL on issue page

### ISSUE THREAD

**Issue by joelpittet** [unicorn-fail/dreditor#15]
Add a clone URL on issue page for the project.  To help people creating patches to get access to the code to create the patch against.

`git clone --branch master http://git.drupal.org/project/node_export.git
cd node_export`

Even if this was just a link to git instructions
https://drupal.org/project/node_export/git-instructions

it's to help people making patches get access to the right branch to patch against

**Comment by markhalliwell** [comment]
Interesting idea, not opposed to this. Anyone else have thoughts on this?

**Comment by YesCT** [comment]
Hm, maybe a link instead to a generic "how to work on an issue". And that would say where the clone link is for a project. Although... "how to do a task" aka "contributor task" document might be even better. 

More like: https://drupal.org/node/2013222

so if one of the remaining tasks was to create a patch there would be a link to do that.
if the remaining task was issue summary update, then they do not need the repo...

**Comment by joelpittet** [comment]
@YesCT  I think that link would be good for beginners and maybe a separate feature request?

This is aimed at seasoned developers who know how to create patches and just want to do it.  
Workflow:  
- find bug in contrib module
- create issue for bug (assuming not already created)
- pull down the latest dev branch (this is where the clone link comes in)
- make fix and create patch

**Comment by joelpittet** [comment]
Also, the feature i'd hope would be like the clone url on github. See screenshot:
https://www.evernote.com/shard/s8/sh/1b2c2b5f-704b-4ba4-b729-6a09c2e7ff56/77dbd4d8e171f49d37a8223061f75a83

**Comment by joelpittet** [comment]
Here's what I think it would look like: 
https://www.evernote.com/shard/s8/sh/c03dc6f5-16a7-4351-8f33-d16a627fdec4/946a17eb5932d302718d1f285872cf85

**Comment by wimleers** [comment]
Doesn't that really belong on the project page? GitHub also doesn't show that for every issue; only on the project page.

This would feel very out of place on issue pages.

**Comment by markhalliwell** [comment]
Hmm, I tend to kind of agree with @wimleers. I wouldn't mind putting this on the main project page though.

Another idea, maybe we could have an "Apply patch" button? This could pop up a list of common shell cmds necessary for the patch (ie: clone repo, curl patch, apply patch, create diff, etc). Thoughts?

**Comment by joelpittet** [comment]
Having it on the project page would still save me a step.  Just following my own workflow for fixing buggered modules.  Find/Create issue, clone repo, apply changes, create patch, upload patch.  The Git repo link is 2 pages out of reach.

I also like that apply patch idea @markcarver maybe open that up as another issue too?  
"curl http://url.patch | git apply" ftw ;)

**Comment by davereid** [comment]
Definitely no on issue pages.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#51
