### ISSUE TITLE
parse needs tags, show a list that links to contributor task docs

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#16]
I wonder if dreditor could do something like https://drupal.org/node/2013222#comment-7511433

And for any needs tags on an issue, have a section (near the summary?) that shows what the issue needs and links to the contributor task instructions to do them. 

I guess dreditor would have to maintain a list of tags and the corresponding links to the contributor task documents.

why?
1) as a demo, to show d.o infrastructure people or motivate people to help those folks to implement it
2) might be useful on it's own as part of dreditor (but really the idea is to help new contributors and new, or potential new, contributors may not have dreditor)

mock up from @joelpittet 
![skitch](https://f.cloud.github.com/assets/1970586/1172430/2d6c74f2-2121-11e3-9c09-5f3f24f700a7.png)

**Comment by joelpittet** [comment]
I like this idea very much!  Good point about maintaining the tags to links.  There is something like that on mentoring hours... http://drupalmentoring.org/task-info   maybe that site could have a service that feeds the associations?

**Comment by joelpittet** [comment]
https://www.evernote.com/shard/s8/sh/492cb16d-180e-459a-a6c6-afe0c3f210cd/4c8dd7fc00e2df1aad18d43a7ea3a0db

and the HTML snippet that generated that look.

```
<div style="width: 25%; float: left; border: 1px solid #ccc; margin: 0 5px;" class="summary">
        <div style="padding: 7px 10px; font-size:12px;">
            <h3>
                Contributor task instructions
            </h3>
            <ol>
                <li>
                    <a class="ext" href="https://drupal.org/contributor-tasks/backport">Backport a Drupal Core patch</a><br>
                    <small style="color: #999">Needs backport...</small>
                </li>
                <li>
                    <a class="ext" href="https://drupal.org/contributor-tasks/write-issue-summary">Write an issue summary</a><br>
                    <small style="color: #999">Needs issue summary update</small>
                </li>
                <li>
                    <a class="ext" href="https://drupal.org/contributor-tasks/add-steps-to-reproduce">Document STR</a><br>
                    <small style="color: #999">Needs steps to reproduce</small>
                </li>
                <li>
                    <a href="https://drupal.org/contributor-tasks/write-tests" class="ext">Write a Drupal core automated test</a><br>
                    <small style="color: #999">Needs tests</small>
                </li>
            </ol>
        </div>
    </div>
```

**Comment by wimleers** [comment]
Wow, beautiful mock-up, @joelpittet. At first I wasn't really convinced, but now the value is clear!

**Comment by markhalliwell** [comment]
I definitely love this idea. Like @joelpittet said, this kind of functionality is very similar to drupalmentoring.org and how it handles tasks. Yes, ultimately I think this should be a part of d.o's customization. However, I think implementing something similarly basic would indeed show benefits and help enforce why this would be needed as d.o code.

I am definitely postponing this feature for now though. I would like to see the D7 migration happen before any further features are added. This is mainly because I will most likely have to fix a lot of Dreditor's existing d.o mods so they work properly with the new D7 underlying markup/features.

**Comment by YesCT** [comment]
Good point about postponing. 

But part of the point is to do it in dreditor because the time to a d7 migration and then getting it implemented there is a possible unknown (long) time. :/

I am working on getting it in d.o too. But I'm new at working on d.o itself. So that will slow me down there too.

**Comment by joelpittet** [comment]
One thing that would help move this along would be a JavaScript mapper for tags to links.  The tricky one will be the ones that need a little regex like `/^Needs Backport/i` but given an array of tags map them to their appropriate links and possibly weight them so that the order is somewhat organized.  So @YesCT  could you make a three column table in excel with the tag names and their associated link and link label?  Then we can see how much will need regular expressions and possibly any other oddities that may come of this.

**Comment by YesCT** [comment]
https://docs.google.com/spreadsheet/ccc?key=0AtDYnjV5l0uydDJ5dU1WZ1ZFQ1lSX19PTEh0eWRsR0E#gid=0

**Comment by YesCT** [comment]
I have a worry that the _numbers_ on the list might imply an order they should be done.
I think a ul would be better.
Also the numbers would change as the tags came and went. (They get removed when the task does not need to be done. And new ones get added as new tasks need to be done.)

**Comment by joelpittet** [comment]
Fair enough, the OL was hopeful that the tasks had order that could be weighted.  That can go to UL if that's too tricky.

**Comment by YesCT** [comment]
More variations at https://drupal.org/node/2013222#comment-7937675

B) is reasonable for dreditor to be able to do I think. Posting that directly here.
![more-links](https://f.cloud.github.com/assets/1970586/1276619/1b11b5b8-2e7f-11e3-8966-b27a725378fa.png)
source: https://drupal.org/files/dreditor-more.txt

This is uses a ul, replaces the tags section. and uses a general (more), or (more info) link. 
If we keep a table of the tag, link, and link text anyway, we can use (instructions) for links to contributor task documents. and (more) for other stuff.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#50
