### ISSUE TITLE
Replace (parts) of autocomplete plugin with external library

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#160]
http://ichord.github.io/At.js/
http://yuku-t.com/jquery-textcomplete/

Primary potential:
1. `@` username autocomplete selection
1. `#` comment ID/link autocomplete selection

Some other autocomplete sub-plugins may have to stay as-is, because:

It's not clear whether either of both supports some of our autocompletions (look-behind for an arbitrary string/regex + "decorate" that value [identically] with wrapping HTML markup when TAB is pressed)... come to think of it, that's not actually "autocomplete" functionality, because your input is not actually completed; it's only "formatted".

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729
