### ISSUE TITLE
Inject a better issue tag autocomplete library

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#162]
Wanted to do this for a long time already, but always forgot to create an issue for it...

Problem
- Drupal's autocomplete.js sucks hard.

Goal
- Facebook-alike tagging.

Options
- http://harvesthq.github.com/chosen/ (jQuery | Prototype)
  - http://ivaynberg.github.com/select2/ (fork of Chosen pre-1.0)
- http://loopj.com/jquery-tokeninput/ (jQuery)
- http://brianreavis.github.io/selectize.js/ (jQuery)
- http://xoxco.com/projects/code/tagsinput/ (jQuery)
- http://textextjs.com/ (jQuery)

NOT options (different)
- http://twitter.github.io/typeahead.js/ (single value)

Related issues
- Drupal core: https://drupal.org/node/1271622
- Dreditor:
  - #16 - special behavior for _"Needs *"_ tags
  - #27 - "button" to trigger UI for editing tags
  - #32 - Personalized settings + e.g., per-user most frequently used tags

**Comment by markhalliwell** [comment]
FWIW, I like http://brianreavis.github.io/selectize.js/ way more than any of the others.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729
