### ISSUE TITLE
issue.summary plugin is obsolete due to d.o UI changes

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#168]
Objective
- The issue.summary plugin (Ajax-driven in-place editing of an issue's summary) is obsolete, since the issue summary is part of the issue comment/update form now.

To analyze
1. This plugin contains some good assumptions about removing overly verbose stuff for d.o power users (Dreditor users).
2. …also a pretty fancy plugin that truly achieved pure awesomeness in ~90 LoC :kiss:

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729
