### ISSUE TITLE
Opera integration seems to not be working

### ISSUE THREAD

**Issue by The-Judge** [unicorn-fail/dreditor#17]
Hi there,
I'm using Opera 12.16 on x86_64 Linux. I installed dreditor as a userscript and the indicator on dreditor.org also report "dreditor is installed!".

But when I go to issues on drupal.org, there seem to be no enhancements like in Firefox.

**Comment by markhalliwell** [comment]
I have no real way to test this or even begin to debug this. I am on a Mac and have the latest Opera 16.0.1196.73 installed. AFAIK, Opera _used_ to be supported, however I am not entirely sure if it still actually works (I don't use it and haven't done a lot of testing with it, yet).

FWIW, plans _are_ in place to support a native Opera extension. However, this extension would only be for the webkit based versions (15+). Older, legacy, Opera versions will not be "actively" supported (mainly due to how few total Opera users there are, regardless of which OS it's ran on).

For now, I am just going to close this issue as I am well aware of the lack of Opera integration. My goal, again, is to have native extensions (for all browsers) so people don't have to rely on the antiquated user scripts.

**Comment by sharique** [comment]
Opera is using same engine as Chromium as so supporting opera should not be be a problem now.

**Comment by markhalliwell** [comment]
They use the same engine, webkit, yes. However, their extensions are built differently than Chrome.

**Comment by The-Judge** [comment]
Opera changed their engine from self developed Presto - Engine to WebKit. Many features which were available in Presto do not run in the new WebKit Edition up until today. Also, this change came along with a major change of look and feel, too, which makes many Opera fans still use the older Version 12 of Opera.

**Comment by anavarre** [comment]
Wonder if this is going to be won't fix or if there's anything that can be done to bring minimal support? I've tested Opera 25 beta on Linux with the Webkit engine and it works so well I'm tempted to switch to Opera permanently. Not having dreditor support for it would make me think twice, though :)

**Comment by markhalliwell** [comment]
It's not a "won't fix" per se. It's just very low priority at the moment as the user base is [likely] very small. Pull requests are welcome.

**Comment by anavarre** [comment]
Sure, I understand that. Think I'll have to lobby for that with @theodoreb

**Comment by theodoreb** [comment]
Not using opera 12 anymore sadly.
