### ISSUE TITLE
[policy] When to use jQuery or native DOM element properties

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#174]
Following my realization in https://github.com/dreditor/dreditor/issues/172#issuecomment-44144774, I'd like to make a decision about this and remain consistent.

The outcome of this will need to be stated clearly in https://github.com/dreditor/dreditor/blob/1.x/CONTRIBUTING.md#coding-standards

**Comment by sun** [comment]
Personally, I'd prefer to not do a "wildcard" policy, but instead, use more sensible _contextual_ rules of thumb. — Much rather _common sense_.

The only sensible concern that can be raised against jQuery/methods is the potential performance overhead of creating jQuery objects in the first place.

That, however, _should_ be evaluated depending on context:
1. Code that runs via DOM.ready on all pages at all times and thus affects the page rendering speed SHOULD be optimized.  Not over-optimized, just optimized.
2. Code that only operates upon user interaction SHOULD use whichever construct is most _readable_ and most _simple_, because performance & involvement of jQuery doesn't matter at all, as you'll hardly be able to measure any significant difference in user experience.

**Comment by markhalliwell** [comment]
Except that when you do things like `this.getAttribute('data-uid')`, my reaction is to say "Ok, well if we're going to native JS, then flush it out and add more fallbacks". So I created the issue #172 to do just that, but then you asked if that's really just `$.data()`... so I'm just confused as to which what validates as "common sense" as you put it.

This inconsistency and constant switching is why I started this issue. It's not to say one way is right and one way is wrong (I can certainly do both). Instead it is to provide a "general rule of thumb" and say:

"Always use "X" method unless you have good enough reason in justifying a different approach (ie: real performance benchmark proof)".

In my eyes, we should either:
1. Go with jQuery methods (preferable). Once we can land #156, we can use jQuery 2.0+ which has significant performance improvements over 1.4.4 (which is what d.o is currently running and effectively Dreditor).
2. Use native JS methods and create methods to handle fallbacks accordingly (#172). This has more overhead.

**Comment by markhalliwell** [comment]
FYI, this is what I meant by this "policy":
https://github.com/dreditor/dreditor/blob/1.x/src/js/plugins/issue.clone.js#L18-L22

We should always use jQuery methods (IMO), but in the rare case it doesn't work or there is an ample reason to justify using native JS (performance, simpler, etc.), we should document via comments _why_.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#22
