### ISSUE TITLE
Add real dreditor logo

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#186]
Just putting this here as a something that needs to happen.

We really need to stop using the Druplicon.

**Comment by sphism** [comment]
Let's make a badass Judge Dredd Style Druplicon to judge all the dodgy code people write in their patches ;)

**Comment by markhalliwell** [comment]
@sun, would like to get your feedback from Matt Terry above ^. He emailed me this link:
https://www.google.co.nz/search?q=judge+dredd+icons&rlz=1C5CHFA_enGB503GB504&espv=2&es_sm=119&tbm=isch&tbo=u&source=univ&sa=X&ei=XzTXU7HOEcv48QWb3IBA&ved=0CBoQsAQ&biw=1389&bih=785

**Comment by markhalliwell** [comment]
FWIW, it'll have to be pretty generic if we did, we cannot run into any copyright infringements whatever we decide.

**Comment by markhalliwell** [comment]
@sun, also, I am curious. Do we need to or should we stick with the "Druplicon"?

**Comment by sun** [comment]
A few thoughts, not meant to be final, just some initial reactions:
1. I smiled when I (slowly) realized the subtle connotation in Dredd — Dreditor.  (If that was supposed to be super-obvious, it isn't.  Also, I only smiled, I didn't LOL.)
2. I'd be hesitant/cautious to associate _"judge"_ with Dreditor.  A _judge_ normally has an absolute decision power, and all legal related stuff is usually perceived negatively.  Dreditor is perceived negatively by some already, primarily due to too many nitpicky reviews.  It would be beneficial to associate and think of Dreditor as something positive that helps to improve quality, collaboration, and contributions.
3. I don't think we need to stick with Druplicon in any way (IIRC we concluded so in the past already).  We may credit the roots/origin by incorporating the infinity eyes/@sun⁣-glasses ;) in some way, but don't have to.

Thoughts?

**Comment by markhalliwell** [comment]
Heh, didn't realize 1), but that _would_ be kinda funny (to some).

2) Yes, I kind of had the same concerns (in the back of my mind) actually. There is definitely some who perceive Dreditor very negatively. I would like to to steer clear of enforcing this belief through branding in anyway. Dreditor is supposed to enhance a user's experience; give them the tools necessary to be productive. It is certainly not meant to "bring down the hammer" so to speak on those that don't conform to standards, just point them out in an easier to read review comment.

3) I thought so, but was not entirely sure. Just asking for clarification so @sphism isn't limited in other potential, more positive, solutions.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#19
