### ISSUE TITLE
Sticky issue form properties

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#199]
Would love to see a new plugin that works similar to _sticky table headers_ in core, but:
1. Makes the main issue property form fieldset sticky when scrolling down.  
   AND
2. Ensures to inject additional vertical padding/margin for exactly the height of that fieldset, so that the sticky elements don't confusingly overlap with the remainder of the form.

Note: Not sure whether this can be accomplished with pure CSS3+ in modern browsers.  If so, even better. ;)

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#18
