### ISSUE TITLE
Switching from a PR build back to original is not easily possible.

### ISSUE THREAD

**Issue by clemens-tolboom** [unicorn-fail/dreditor#202]
1. Visit https://dreditor.org/development/build
2. Select a build ie #93
3. Next visit https://dreditor.org/
4. Everything seems ok but it should tell something different

It could be possible to add the PR id into the build I guess.

**Comment by markhalliwell** [comment]
I've discussed this with @sun in IRC. Basically we need a way to override the package name/title (currently `Dreditor`) in the build process. This is a complicated issue given how it's currently setup:
1. Add a grunt option that allows the override of the package json title, ie: `--title="Dreditor (PR #93)"` or `--title="Dreditor (1.x)"`: https://github.com/dreditor/dreditor/blob/1.x/Gruntfile.js#L9 and https://github.com/dreditor/dreditor/blob/1.x/Gruntfile.js#L20
2. Somehow figure out a way to alter https://github.com/dreditor/dreditor/blob/1.x/autobuild.json#L7
3. Amend the necessary autobuild step in: https://github.com/dreditor/dreditor.org/blob/7.x/sites/all/modules/custom/dreditor_org/dreditor_org.drush.inc#L72

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#17
