### ISSUE TITLE
Consider to incorporate qa.d.o notifier extension

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#204]
https://github.com/Lullabot/drupal_qa_notifier by @justafish

We should probably come up with a plan for how to operate with the different browser/extension APIs... I assume that a few (simple) abstract wrapper proxy objects/services could do the trick.

**Comment by justafish** [comment]
We talked about this at the sprints and decided to keep it as a separate extension instead of incorporating it into dreditor for now. Maybe when I've finished the extensions for Firefox and Safari, since it's using some specific chrome stuff at the moment and I'll probably still be making changes to the qa.drupal.org feeds.

**Comment by markhalliwell** [comment]
Awesome :) I'd definitely be interested in incorporating more of an abstracted "event" listening handler in Dreditor. Then we can move forward with many of our "plugins" as native extensions opposed to hacky DOM injection/manipulation as a whole. #156

**Comment by larowlan** [comment]
And a Firefox port https://github.com/larowlan/drupal_qa_notifier

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#16
