### ISSUE TITLE
CSS issue with dreditor 1.2.9 and Firefox 30.0

### ISSUE THREAD

**Issue by anavarre** [unicorn-fail/dreditor#213]
Please see attached. Patch filenames seem to be trimmed.

![patch-filename-issue](https://cloud.githubusercontent.com/assets/293478/3403619/f8ddaade-fd67-11e3-8bd4-04d3ecfa81ea.png)

Here's how I temporarily fixed it:

![patch-filename-fix](https://cloud.githubusercontent.com/assets/293478/3403623/0b553420-fd68-11e3-9aaf-cb86ed14cb69.png)

FYI I have the browser zoom set to 150%

**Comment by sun** [comment]
> FYI I have the browser zoom set to 150%

Does this also happen on zoom 100% ?

If it doesn't, then it's a native zoom bug of Firefox (wouldn't be the first one).

Regardless of that, the "quoted" CSS looks very phishy to me; can't see why those styles would be required in any way.  Wouldn't mind to remove them either way.

**Comment by anavarre** [comment]
Unfortunately I can't test zoom 100% now. The trigger is a new (untested) patch. When the bot has tested it, it displays just fine.

I'll report back when I can test things more. Thanks!

EDIT: hmm, a new (untested) patch with a name long enough for this issue to be reproducible.

**Comment by anavarre** [comment]
I could see it again today and reverting to zoom 100% didn't change anything. It's actually even worse as the d.o. page layout goes awry (uncentered), too. I also tried without having my Firefox zoom extension on but it didn't change anything.

![testbot_request_sent](https://cloud.githubusercontent.com/assets/293478/3443894/8263ded6-0128-11e4-9bf0-f1632dedb71d.png)

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#15
