### ISSUE TITLE
Avast! antivirus claims Dreditor is a risky browser plugin

### ISSUE THREAD

**Issue by tsvenson** [unicorn-fail/dreditor#214]
Avast! on my Windows machine today alerted me that there are three _dangerous_ browser plugins on my system. One of their claims was dreditor.

This was the first time I've seen Avast warning about browser plugins so I suspect it is a new feature they have added.

Just wanted to let you know this is happening.

**Comment by markhalliwell** [comment]
Its possible this is due to Dreditor being injected/ran directly on the page rather than ran as a true background (extension) script.

ref: #204, #155

**Comment by tsvenson** [comment]
That's a likely cause yes. Avast! most probably have a way of requesting whitelisting from that. I'll take a look shortly if I can find out how to do that.

**Comment by tsvenson** [comment]
Here's the screenshot:
![avast_dreditor](https://cloud.githubusercontent.com/assets/444455/3421131/8cdfa882-fed9-11e3-87cf-b5041868c184.png)

The part of the text that is quite weird for me is "bad reputation _among_ avast users". Would be quite surprised if any serious d.o user have reported it. Doesn't make much sense to me.

I tend to believe it is more their own _tools_ that have somehow made that claim.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#14
