### ISSUE TITLE
Hide issue when clicking "updated" marker if issue-hiding is enabled

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#216]
Context:
1. You can enable the "Hide unimportant issues" feature for d.o issue queues.
2. An unread issue that has been updated (with a new comment) does not get hidden.
3. If you're aware of the update already, you can click the updated marker to mark the issue as read (which issues a HEAD request to the d.o issue in the background).

Currently, given (1) and doing (3) only marks the issue as read, but the table row still remains to be visible.  The row only disappears after reloading the page.

It would be great if clicking the updated/unread marker would additionally hide the table row (if the setting is enabled).

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#12
