### ISSUE TITLE
disable dreditor for security.drupal.org

### ISSUE THREAD

**Issue by pwolanin** [unicorn-fail/dreditor#218]
security.drupal.org is scheduled to be upgraded to Drupal 7 soon.

Please disable dreditor for that domain - the fact that it loads external assests is a potential risk.

**Comment by markhalliwell** [comment]
xref: #75 

Curious. In what way? The only external source I am aware of is jQuery UI (which needs to be removed anyway: #173). In the mean time, if that is really the issue, then I'm sure we can simply load jQuery UI manually from whatever *.d.o site we're on instead of Google's CDN.

I would prefer not to modify the domain permissions again. Every time these are changed, Chrome will disable it and force the user to manually re-enable them and confirm that these changes are approved.

**Comment by pwolanin** [comment]
Yes, its js and css for jquery-ui

**Comment by markhalliwell** [comment]
After discussing this with @pwolanin, I think we should just proceed with #173 and get rid of (edit: jQuery UI dependency) ~~this~~ once and for all.
