### ISSUE TITLE
Patch/diff coloring/highlighting does not recognize --irreversible-delete

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#222]
We recently fixed coloring/highlighting for renamed/copied files in #200.

Irreveserible deletions are not covered yet:

``` diff
diff --git a/core/modules/system/src/Tests/System/ScriptTest.php b/core/modules/system/src/Tests/System/ScriptTest.php
deleted file mode 100644
index 0be6217..0000000
```

The line starting with `deleted file` should be colored like removed/deleted code.

**Comment by sun** [comment]
Heh.  Apparently, GitHub's Linguist library isn't aware of that diff header either yet. :wink:

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#11
