### ISSUE TITLE
Make it easier to write change records

### ISSUE THREAD

**Issue by dawehner** [unicorn-fail/dreditor#228]
It is a bit annoying if you start to write a change record that you have to type in Drupal core and the actual issue.

What about introducing some button in issues which allows you to create a change record targeted to that issue.

**Comment by jibran** [comment]
+1 to the idea

**Comment by sun** [comment]
I looked into this some time ago already, but got stuck on the problem of determining the correct form input values (as those are in an a weird autocomplete format).  Need to check whether I still have that code.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#9
