### ISSUE TITLE
Ability to test project in simplytest.me

### ISSUE THREAD

**Issue by rpayanm** [unicorn-fail/dreditor#229]
In the any project page for example: https://drupal.org/project/views there is a possibility of try out a demonstration in simplytest.me.
See the imagen in the attachment.
![views](https://cloud.githubusercontent.com/assets/6087454/4323521/15587c18-3f51-11e4-8448-c426b2dc33e5.png)

**Comment by star-szr** [comment]
That looks pretty tight, we can't really squeeze that button in beside 7.x-3.x-dev I don't think. In general I like the idea though :)

**Comment by rpayanm** [comment]
The button can be in any other place, my image is only for understand the propose.

Greetings.

**Comment by klonos** [comment]
++

I was about to file an issue to request this feature myself.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#8
