### ISSUE TITLE
Button to insert beta phase evaluation

### ISSUE THREAD

**Issue by xjm** [unicorn-fail/dreditor#233]
See: 
https://www.drupal.org/core/beta-changes
https://www.drupal.org/node/2373483

We should add a button to Dreditor to insert the beta phase evaluation template in https://www.drupal.org/node/2373483 so that contributors can easily fill out the table. We originally were going to add it to the issue summary template, but since most issues that need evaluation exist already and only Drupal 8 core issues need the table, it would be better UX to have a separate button.

**Comment by markhalliwell** [comment]
Closing in favor of #93.

**Comment by xjm** [comment]
No, this is not a stock response -- it is a requirement for Drupal 8 issues during the beta.

**Comment by markhalliwell** [comment]
So.. not gonna close (knee jerk reaction because I would prefer #93 -ish and I really don't have time to work on this). Talked it over with @xjm and this is something that's needed for D8 stuff like right now. If someone can implement a PR for this, similar to how #147 was done... much would be appreciated on all fronts.

**Comment by star-szr** [comment]
I can work on this tonight or possibly during core mentoring if it's not too busy.
