### ISSUE TITLE
Improve @mention functionality

### ISSUE THREAD

**Issue by lewisnyman** [unicorn-fail/dreditor#237]
Compare the dreditor and github @mention functionality and you can see there is a lot to improve.

I wasn't sure if there was already an issue for this. I'm happy to work on this.

**Comment by lewisnyman** [comment]
I found this really good looking lib: https://github.com/ichord/At.js
I'm haven't figured out how to integrate it into suggestions yet.

**Comment by markhalliwell** [comment]
Heh, yes I am familiar with At.js :)

I found this issue (https://www.drupal.org/node/448074) and started to champion Alli (@heylookalive) to look at it because he created https://www.drupal.org/project/atjs which is the Drupal bridge for At.js.

I have put a lot of thought into this actually and definitely want the feature too, but I think it would be more cost effective to utilize d.o for this task.

There are, however,  a few problems I encountered with trying to put this in Dreditor:
1. To properly "mention" someone, there has to be access to their private email to send an email notification (which Dreditor doesn't have). We could possibly "fake" this by loading a hidden AJAX request to the mentioned user's contact page, to send a "Hey I mentioned you here" email.
   - This doesn't always work. Not everyone has their contact enabled.
   - This ties into/defeats user preferences of being contacted.
   - This deserves it's own setting asking if they want to be notified of "mentions" (I suspect many that don't allow direct contact, wouldn't mind being mentioned).
   - Only Dreditor users would have this.
2. There is added complexity for determining what a user's UID is if they haven't already commented on the issue. This means yet another AJAX request.
3. Autocomplete. There needs to be a callback that queries everything after `@` and provides a list of possible users.
   - This, in theory, could be accomplished by limiting to only the users currently listed on the current issue/page.
     - This kind of defeats the whole point of having autocomplete though. For instance, Alli wasn't on this issue, but I mentioned him above and he will now get a notification for him to start participating, or at the very least see the issue ;)

I would prefer to close this issue in favor of the d.o one, but if you can come up with a reason not to just let me know.

**Comment by lewisnyman** [comment]
Ah yes, so the functional improvement of a mention notification isn't what I had in mind in this issue, which is very much in the realm of d.o.

I think I meant more of a design improvement, if you compare the UI for autocomplete on Github and Dreditor, there is a big difference.
1. Only one suggestion shown at a time
2. The tooltip is shown at the bottom of the screen and is easy to miss.

Maybe that's it. I think if we do keep autocomplete in Dreditor the UI could be a lot better. Does that make sense?

**Comment by markhalliwell** [comment]
Yes, it makes sense. I have just been waiting to see where that d.o issue would go. I am really not sure if we need or should improve the existing "autocomplete" feature of Dreditor. I would much prefer that we have something that is natively supported on d.o.

Adding third party libraries in an extension (which is then loaded on a page) is a rather, unsanctioned, action at best. Currently, Dreditor is injected directly into every page of d.o via a `<script>` tag. Adding a 3rd party library to this injection may complicate matters further. I would prefer to move away from this old content script injection method.

**Comment by markhalliwell** [comment]
Unsanctioned by https://addons.mozilla.org is what I meant.

**Comment by dawehner** [comment]
One thing which is certainly annoying in the current UI is that autocompletion stops at some point.

For example when alexpott is part of an issue you have to type @a< tab >, but not @al< tab >, because this doesn't work.

**Comment by markhalliwell** [comment]
I am certainly not disagreeing. Yes, the autocomplete feature is inconsistent and could definitely be improved. It's all custom and closely tied in with the `#N` and `<...` features. Decoupling/updating this will take some effort for sure.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#7
