### ISSUE TITLE
REVIEW button does not open linked patch but previously hidden patch

### ISSUE THREAD

**Issue by derjochenmeyer** [unicorn-fail/dreditor#24]
- review a patch clicking the REVIEW button
- hide the patch clicking the HIDE button
- read on and forget about the hidden patch
- click REVIEW on another patch

This will not open the new patch but the previously hidden patch. This behavious is quite confusing. Clicking REVIEW on a patch should always open THAT patch.

**Comment by star-szr** [comment]
I think the problem with making this change right now with the current implementation (maybe @markcarver can confirm) would be losing reviews, which we desperately don't want to happen. I agree the current behaviour is confusing though.

**Comment by derjochenmeyer** [comment]
How would this result in losing reviews?

**Comment by star-szr** [comment]
See https://github.com/dreditor/dreditor/issues/5#issuecomment-23439822 for longer term ideas on an interface that would allow switching between patches in a more sensible way. The way I see it having REVIEW always open the given patch would be equivalent to clicking 'CANCEL' on the pending review. Because from my experience Dreditor has no way of reviewing multiple patches at the same time, it can only maintain a code review for one patch at a time.

So you would:
Click REVIEW on patch A, patch A opens
Add some comments to patch A with the patch review tool
Click REVIEW on patch B, patch B opens
(optional) Add some comments on patch B with the patch review tool

I think comments added to patch A would be gone with no warning as soon as you click REVIEW on patch B.

**Comment by derjochenmeyer** [comment]
True, but during the COMMUNITY TOOLS WORKSHOP at DrupalCon Prague nobody could explain why dreditor showed the "wrong" patch.

What about a simple "alert"?

"You are currently reviewing patch XY. If you open this patch all comments made to the previous patch will be lost. Do you want to continue?"

**Comment by star-szr** [comment]
I'm not totally opposed to that idea but with the JavaScript alert losing your work is only a keystroke away. I definitely agree it's confusing, I'm not trying to justify the current functionality at all! :)

We also have #26 where we discuss auto-saving reviews and that would make a change like this a much easier decision.

**Comment by sun** [comment]
Some time ago, my original plan/idea was to minimally adjust the current patchReviewer sub-app implementation, so as to able to spawn multiple instances of the app's interface.

That would not only resolve this issue, but in addition, enable concurrent patch reviews (for comparison purposes).  I played with the idea of simply vertically stacking multiple patchReviewer UIs, and add some extra fanciness for that purpose, e.g., linking the scrollbars to each other (scrolling through one patch scrolls through all patches at the same time), and likewise for the jump navigation links.

Doing that shouldn't be too hard — the main patchReviewer app code is encapsulated already (just needs to be changed to be instantiated).

Same for the main Dreditor overlay setup/teardown methods — speaking of, the original idea was that this overlay could be re-used by other apps than the patchReviewer, but in the meantime, that total-screen-takeover-overlay interface approach is still only used by patchReviewer (other apps are using more granular/specific interface widgets), so when doing this, it would be best to move this premature interface abstraction into patchReviewer.setup() + .tearDown().
