### ISSUE TITLE
Reorganising files breaks table. Oops!

### ISSUE THREAD

**Issue by kattekrab** [unicorn-fail/dreditor#243]
I reorganised the files on this issue
https://www.drupal.org/node/853800 

and it kind of went a bit whacky.

screenshot
![dreditor-files-table](https://cloud.githubusercontent.com/assets/172755/5627950/4c228c3a-95f4-11e4-82d0-65c7e1454d6e.png)

**Comment by star-szr** [comment]
Well that's different. Thanks for the report, we'll look into this!

**Comment by star-szr** [comment]
I actually saw this on a different issue a couple weeks ago but wasn't able to pin down the cause (lost the markup). Seems very edge case-y. Luckily the issue you posted still has this problem visible so I think this can be worked on. I unfortunately don't know when I will have time to debug this but just thought I would update here :)

**Comment by kattekrab** [comment]
Thanks!  And Happy Hunting ;)

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#5
