### ISSUE TITLE
"Clone issue" button should not clone status or "Triaged D8 critical" tag, and possibly not "critical" priority

### ISSUE THREAD

**Issue by xjm** [unicorn-fail/dreditor#245]
Recently, there have been a lot of issues posted as critical by mistake because contributors use the "Clone issue" button to create followups for criticals. This is especially problematic when the issue has been marked as "Triaged D8 critical" by the branch maintainers and the button clones that tag, which is for maintainer use only. Creating issues with this tag completely defeats the purpose.

Also, in general, I think cloned issues should be created as "Active", which is normal for a new issue. It's very unlikely that you want to clone a new issue that has exactly the status of its parent.

**Comment by YesCT** [comment]
yeah, this would really help.

**Comment by YesCT** [comment]
another thing (might be difficult) 
would be to check when saving,
if the title of the new clone is the same as the source issue that it was cloned from,
have dreditor give a message: 
you forgot to update the title

or something. and not let the issue be saved.
OR
save it, and then put up the message that will remind people to change it.
that would be super fine.

**Comment by star-szr** [comment]
I would propose we change the clone behaviour to always:
- Set priority to 'Normal'
- Set status to 'Active'

As for the "Triaged D8 critical" tag, we could create a blacklist of tags that are not to be cloned, my only concern there is maintenance. If we can make that list something easy to create PRs against I'd be fine with that.

@markcarver @sun any other thoughts? Otherwise I'm happy to work on this in the near future.

@xjm would getting the first 2 changes (priority and status defaults) in relatively quickly help? Those should be quick to implement and integrate.

**Comment by xjm** [comment]
Yep that would help for sure!

**Comment by sun** [comment]
The proposed change would hard-code custom assumptions that are not universally true.
- When cloning an issue that is postponed, I expect the cloned issue to be postponed, too; not active. Same for needs-more-info.
- When cloning an issue that is major/critical, I expect the cloned issue to have the same priority.

To me it sounds like you're trying to clone the suboptimal/wrong (base) issue.

**Comment by xjm** [comment]
This isn't a change I, personally, want for my convenience because I don't know which issue I should clone and can't be bothered to set the status fields myself. It's a suggestion to try to fix the 80% usecase of the button, which is people creating active sub-issues or followup issues in the core queue. The fact is, many issues created using the button get saved with the wrong values in one or more fields, sometimes in a way that is disruptive, and usually in a way that is at least annoying.

**Comment by star-szr** [comment]
Agreed about the 80% use case. Usually when I'm cloning I'm going for:
- Title (sometimes)
- Project
- Category
- Version
- Component
- Tags
- Issue summary (sometimes)

It might be instructive to look back to when this functionality was first introduced.

**Comment by YesCT** [comment]
I think it is ok to special case what to do when cloning a critical. At least in core.
Default to Normal, or ... dont fill in the priority when cloning a critical to make people pick it. 
Might make them think.

When cloning a major, normal, or minor, I think we _should_ default to the same priority.

I also think it is ok to special case some tags that do not get added.
As for maintaining that list, once the functionality is in dreditor, pull requests to change it will be somewhat easy for us.

It is putting the functionality in that less people can do.

**Comment by markhalliwell** [comment]
IIRC, the original concept was mainly to clone just some of the basic stuff that are actually relevant. Over time things have been added and I think that we're starting to see the adverse effects of doing so.

From my experience, I think the only things that really should be cloned are as follows:
- Project
- Category
- Version
- Component

The reason I did not include title, tags or issue summary is because those really **should** be unique to the issue and must be filled out properly. Not cloning them forces people to actually fill them out.

Regarding priority:
Just because the parent/related issue is anything other than normal, doesn't mean we the cloned issue should also get the same priority. For instance, a critical issue gets fixed, but it's soon realized that some documentation or minor verbiage needs to be addressed so a follow-up is created. Obviously it shouldn't get the same critical status as it doesn't actually break anything.

Regarding tags:
When cloning an issue, there's usually a 50/50 changes that all the tags are really accurate anyway. Usually it's used to create a follow-up. For instance, an issue that has been mostly front-end JavaScript work may need a cloned related issue for the back-end (PHP) side of things. In which case "JavaScript" doesn't apply. Furthermore, there is a slew of "Needs ...." whatever tags that really shouldn't be cloned either. I personally think we should just avoid cloning them all together. Adding a "blacklist" will only make this 10x more complicated and highly unmaintainable.

**Comment by star-szr** [comment]
I can get on board with that @markcarver.

**Comment by YesCT** [comment]
so. there are really two things: a follow-up and a clone.

imagine a meta.
I clone it to make a child (many fields change a lot, including issue summary, priority, etc... title might be similar a bit but will be pretty different), some tags will need to be removed, but some will stay. summary will be different. (but I dont mind select all and delete, then insert summary)

then I clone that child to make alllllllll the other children. those children will _probably_ be _almost_ exactly the same. same priority, replace one word in the title, etc. tags will probably be all the same.

let's remember both cases please.

I still think, these two things will help a lot, and not remove features people find helpful:
 1) for core, when cloning a _critical_ the priority should be blank so it is a required field and will be forced to choose.
 2) have a blacklist of tags that dreditor doesn't copy over. (the stuff about triaged criticals)

**Comment by markhalliwell** [comment]
So really there's two use cases here: "clone" and "follow-up". Then there really needs to be two different buttons for these and both cases need to stop trying to step on each other toes.

Doing a "special case for core" or having any kind of "blacklist for tags" is a huge no go in my book, very bad DX (for us) and UX (expectation and consistency across both contrib and core).

**Comment by xjm** [comment]
I can understand the concern about the priority field--that there is a reasonable chance you actually do want to clone something with the same priority--and just using the priority of the cloned issue seems fine to me. It'd be bad UX to get a validation error for the field, when the implication is that it would be populated. (For core, we'll triage the criticals, so we don't need to impose that annoyance on contrib... so long as they aren't hidden from us by someone unwittingly creating a new issue with a maintainer-only tag that my queries against nodechanges can't even catch.) :P

I'd think two buttons rather than one would be worse UX, though there are some differences outside those already discussed. E.g., for a followup, the original issue should be a related issue, not a parent issue. And for a child issue, the first line should not be "followup to foo". But these are minor things IMO.

Would a tag blacklist really be so annoying? Just stripping certain values out of the field, from a separate list we could submit PRs to? There are tags like "Needs reroll" that should not, ever, apply to a cloned issue, in core nor contrib.

**Comment by star-szr** [comment]
Minor: Priority defaults to 'Normal'. There is no '- Select -' value. Just mentioning because it came up in a few comments now.

**Comment by YesCT** [comment]
slightly related:
https://www.drupal.org/node/2426711
d.o issue for Add a link to create a child issue to the child issues block

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#4
