### ISSUE TITLE
Dreditor should ignore the messages that Git adds for readability

### ISSUE THREAD

**Issue by nkgokul** [unicorn-fail/dreditor#249]
Git adds some messages like "\No new line at the end of file" to increase the readability. DR Editor should ignore them and not show as error or highlight it as a git directive/message.

![screenshot from 2015-02-10 13 24 26](https://cloud.githubusercontent.com/assets/1375897/6123569/24977a94-b12a-11e4-9540-24eda9c42ee9.png)

**Comment by andypost** [comment]
That's how it supposed to be according https://www.drupal.org/coding-standards#indenting

> All text files should end in a single newline (\n). This avoids the verbose "\ No newline at end of file" patch warning and makes patches easier to read since it's clearer what is being changed when lines are added to the end of a file.

**Comment by nkgokul** [comment]
Hi Andy/Sun,

Thanks for looking into the issue. 

The previous version of the code didn't have a new line in it. So I added the new line to the end of the file and created this patch(The patch applies perfectly). When I tried to review it in dreditor it showed the git comment/directive in red and I was under the impression that I had made some mistake in the new patch. 

Do you think it would make sense to add a "-" before the "\ No newline at end of file", so that the end user knows that it was an error in the previous code and it has been fixed in his new code?

**Comment by markhalliwell** [comment]
Patch in question ref: https://www.drupal.org/node/2419161#comment-9580467

This is a not an issue. As stated above, this is simply how patches are generated by diff/git and is the expected behavior. Subsequently, Dreditor is limited in how it parses the patch. However, Dreditor is displaying the patch correctly.

There is no better method (that I am currently aware of) to properly show the removal of a line without the newline character and the addition of the said fixed line afterwards. In fact, having `\ No newline at end of file` in between the two is actually what indicates that the patch fixes the error.

If there wasn't a `+}` at the end, then it would indicate that this patch instead removed the new line at the end of the file. This issue is more about understanding the syntax of diffs than with how Dreditor parses or displays it.
