### ISSUE TITLE
Add a "simpletestme without patch" button to the issue buttons

### ISSUE THREAD

**Issue by jackbravo** [unicorn-fail/dreditor#250]
So, as part of the DrupalCon sprint in DrupalCon LatinAmerica with @YesCT, we hit the issue that people using the simpletestme button usually also want to test withtout the patch to see how it works with and without the patch. New users usually don't know how to launch a simpletestme instance of head without an explenation. And the select list for a fresh simpletestme site from the homepage is a little daunting.

Could we add a "simpletestme without patch" (or another name) button to somewhere in the page of the issue? We think of two places:
1. At the top of the issue, next to the list of files (before or after)
2. Next to every simpletestme button, either in another line, or before or after in the same line.

**Comment by star-szr** [comment]
Just want to mention, you can click the little 'X' beside the patch, that gets you simplytest.me without the patch. I'd be more into adding a simplytest.me button to project pages, I can't recall if that's been discussed though.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#3
