### ISSUE TITLE
Restore input to check path

### ISSUE THREAD

**Issue by joelpittet** [unicorn-fail/dreditor#254]
I tried the restore input button and it seemed to pick up results from a different node. I didn't realize it also changed the title and tags and issue summary.

It would be nice if the input could check the node id before restoring previous results?

This was how it broke things:
https://www.drupal.org/node/2339447#comment-9908653

**Comment by markhalliwell** [comment]
Unfortunately doing this would cause localStorage to blow up in size (think of how many issues you submit each day and multiply that by a week).

This feature just saves the last form actually submitted (which I am guessing was the other issue you were on).

I'm not entirely sure this can be "fixed" until a more permanent storage solution is implemented.

x-ref: #224

**Comment by joelpittet** [comment]
What about just one, to prevent override? if (nid != last_nid) don't do anything.

**Comment by markhalliwell** [comment]
Honestly, this plugin is an artifact IMO from old d.o and Dreditor days. Chrome has gotten a lot better (not sure about FF) at restoring inputs from closed tabs/windows. I haven't used this feature at all in at least a year.

Also, I'm not entirely sure what it's use case is, I would like to hear from @sun about this if possible to clarify.

From https://github.com/dreditor/dreditor/blob/1.x/src/js/plugins/form.backup.js#L1-L9:

``` js
/**
 * Backs up form values before submit for potential later restore.
 *
 * drupal.org's advanced infrastructure may respond with totally bogus things
 * like HTTP redirects to completely invalid locations. Native support for
 * retaining previously posted form values in modern browsers is entirely
 * hi-jacked in those cases; the browser doesn't even know anymore that it
 * posted something.
 */
```

Which suggests that at some point d.o was unstable and caused a lot of issues with form data becoming missing.

If anything I would argue that we simply remove this "feature" entirely since it's limited and rather confusing.

**Comment by markhalliwell** [comment]
x-ref: #149, #131 

> D7 upgrade, d.o is (completely) eating some of my comments sometimes - my browser performs a GET redirect to the same page, losing all submitted POST data + even browser history, so not even the browser stores the form values in any way...

Personally, I have never seen this happen... which makes me think perhaps it's another extension or a conflict of some kind?

Sure, at first, the D7 d.o upgrade was rather unstable... but that has cleared up quite drastically from what I've seen.

**Comment by markhalliwell** [comment]
P.P.S. (lol)

I was going to suggest something like http://garlicjs.org/, but from reading previous issues and comments, this feature is about what happens _after_ the form is submitted.

> What about just one, to prevent override? if (nid != last_nid) don't do anything.

I'm ok with this concept. However, since #149 added this feature to most forms on d.o, I'm not entirely sure a "nid" will always be present and would be reliable. Maybe we should save the current path when the form is submitted and test against instead.

**Comment by joelpittet** [comment]
I was hearing from a few people that they use it today at the sprint and it saved them(specially on a long and reasoned issue comment). and that's how and why I tried it, but it buggered up the issue so that is why I'm posting the request here. I use FF and don't plan on switching anytime soon.

**Comment by star-szr** [comment]
Lazarus browser extension, available for FF and Chrome at least. Works (almost) everywhere.

**Comment by joelpittet** [comment]
Hmm maybe this feature can be removed?

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#2
