### ISSUE TITLE
Incorrect background

### ISSUE THREAD

**Issue by claudiu-cristea** [unicorn-fail/dreditor#259]
See attachment
<img width="890" alt="red" src="https://cloud.githubusercontent.com/assets/473868/9124207/b22e7c28-3c9d-11e5-9204-24fb0bc437ce.png">

**Comment by claudiu-cristea** [comment]
The patch can be found here https://www.drupal.org/node/2429191#comment-10193717

**Comment by star-szr** [comment]
Thanks for the report, I have seen this myself as well. Usually only on MAINTAINERS.txt patches, mind you :)

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729
