### ISSUE TITLE
Get some part of dreditor back to drupal.org

### ISSUE THREAD

**Issue by gagarine** [unicorn-fail/dreditor#261]
Dreditor enhances user experience and functionality of drupal.org. Having a seperate project make it easier to experiment and quickly change the UI of drupal.org. But some features of dreditor are now very well tested and very useful, so why not pushing them back to drupal.org?

This would be nice for user that don't know about dreditor and also to avoid to have a bigger and bigger layer on top of drupal.org.

**Comment by markhalliwell** [comment]
We have been, e.g. the whole "Credit & Committing" fieldset at the bottom of issues was heavily inspired by Dreditor. There are other smaller features that have made their way in over time as well. Dreditor is, and always has been, the rapid prototype for determining a good way to develop new feature sets for d.o.

However, that is actually becoming less and less of a true statement since d.o's upgrade to D7 (which has allow for much faster and more direct d.o development and deployment).

Something as complex as the current patch reviewer in Dreditor will likely never get in though. Instead they've been focused on trying to integrate something more native to our process.

Regardless, there _is_ the [dreditor feature](https://www.drupal.org/project/issues/search?projects=&project_issue_followers=&issue_tags_op=%3D&issue_tags=dreditor+feature) tag that is being used on d.o already. I suggest following those issues if they interest you.
