### ISSUE TITLE
Assess pift.js

### ISSUE THREAD

**Issue by star-szr** [unicorn-fail/dreditor#266]
pift.js, what is it doing and is it still needed?

I thought after quickly testing in #265 it might be dead code but it's still doing something. Can we remove it?

**Comment by drumm** [comment]
8.x legacy testing is now disabled. For example #32 vs. #38 at https://www.drupal.org/node/2485633. Any customizations around markup that is no longer in #38 should be removed.

**Comment by star-szr** [comment]
I took a bit more time and found what it's doing, and it's not entirely around the legacy testbot, moreso around attachments. I'm thinking we can maybe remove the PIFT specific parts and rename it or look at bringing some of these changes upstream into d.o if possible. Personally I'd probably be fine with just removing it.

**With pift.js**
![with-pift-js](https://cloud.githubusercontent.com/assets/327943/10374241/1bfd514e-6dc0-11e5-89ed-274d5c3678e8.png)

**Without pift.js**
![without-pift-js](https://cloud.githubusercontent.com/assets/327943/10374246/22dd5018-6dc0-11e5-940f-53af1d92a253.png)

Here is #38 from https://www.drupal.org/node/2485633 because it's drupalci only:

**With pift.js**
![with-pift-js-drupalci](https://cloud.githubusercontent.com/assets/327943/10374323/9641b3d2-6dc0-11e5-8e8c-f3da16d9b912.png)

**Without pift.js**
![without-pift-js-drupalci](https://cloud.githubusercontent.com/assets/327943/10374378/e66da9a6-6dc0-11e5-892d-a401a166973b.png)

**Comment by star-szr** [comment]
@drumm thanks for the update by the way. One question though, isn't the legacy testbot markup going to stick around even if it's not used for new tests?

**Comment by drumm** [comment]
Yes, the markup will remain on any patches that have been tested on the old bots.

**Comment by davereid** [comment]
Also note, old bots being used actively for all D6 and D7 (core + contrib)

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729
