### ISSUE TITLE
Enable WebExtension support for Firefox

### ISSUE THREAD

**Issue by bkonetzny** [unicorn-fail/dreditor#268]
Firefox nightly has (limited) support for WebExtensions API, the same API Chrome uses for it's extensions. With a little change in the manifest.json, the Chrome build of Dreditor would be compatible with Firefox (Nightly). It would be great to add the Firefox related metadata to manifest.json to test further builds. Once this is shipped in Firefox, the build process might be unified and thus reduced in complexity. Microsoft Edge is also expected to gain support for the WebExtension API.

**Comment by andypost** [comment]
FF43 is out and dreditor now disabled ;(

**Comment by signalpoint** [comment]
Yes indeed, FF43 and dreditor are now disabled for me as well.

**Comment by star-szr** [comment]
Can anyone weighing in to say Dreditor is also disabled please test the #269 PR? A build is available at https://dreditor.org/development/build.

**Comment by apratt** [comment]
Thx for a great plugin. I tried to install #269 to get my disabled Dreditor back and Firefox kicked me to this page: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by andypost** [comment]
the same for me

EDIT `about:config xpinstall.signatures.required=FALSE` still a workaround

**Comment by mgifford** [comment]
Is the plan to get dreditor signed on officially with Firefox so we don't have to disable the security for this browser? https://developer.mozilla.org/en-US/Add-ons/Distribution

**Comment by markhalliwell** [comment]
@mgifford, see #256

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729
