### ISSUE TITLE
Support for http://pareview.sh

### ISSUE THREAD

**Issue by visabhishek** [unicorn-fail/dreditor#273]
Provide support to review project on http://pareview.sh.
Its help alot to review project online.

**Comment by sriharshauppuluri** [comment]
Good Idea

**Comment by star-szr** [comment]
Need more info, how would this work? I don't see any patch files on this site at a glance.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729
