### ISSUE TITLE
Remind me to upload a patch

### ISSUE THREAD

**Issue by rocketeerbkw** [unicorn-fail/dreditor#278]
An unobtrusive reminder should be enough, and won't get it the way when changing the status and legitimately not adding a patch.

My idea: when the status is "Needs review" and there is no patch uploaded, change the save button to say "Save without patch."

This is kind of the opposite of https://github.com/unicorn-fail/dreditor/issues/31

**Comment by star-szr** [comment]
In general I (and I think @markcarver) would like to see these types of changes incorporated directly into d.o so they can benefit more users. See #263, #261, #238 for some more context.

This feature gets a bit tricky IMO and potentially confusing (especially for new users) because there are many cases where it makes total sense to change the status to needs review without uploading a patch. For example from RTBC to needs review. We need to guess intent and I think that's hard with the data we have.

I also am not sure changing the text of the save button would fix the issue of not uploading a patch, at least for me. I don't usually read buttons in cases like this. It would have to be something more in your face like a JS confirmation or some kind of banner or larger visual than a text change. Similar to how my email client warns me if I put the text "attached" in my message but don't attach anything :)

But in this case I can almost see this type of functionality tying into the issue credit system, where there are checkboxes/radio buttons like:
- I am providing a patch review
- I am uploading a new patch
- I manually tested the patch
- etc.

And then if "I am uploading a new patch" is selected, the file upload field could be mandatory. Just ideas at this point.

**Comment by markhalliwell** [comment]
Agreed.
