### ISSUE TITLE
Make Embed image button respect cursor position

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#28]
https://drupal.org/node/2073499

from @Cottser 
"The idea would be to make it work similarly to the Insert module. So instead of appending to the end of the body, embed the image at the current cursor position if the cursor is in the body at the time of clicking 'Embed'."

I have also wished for this.

**Comment by star-szr** [comment]
Thanks! I closed the d.o one as a duplicate.

**Comment by DevElCuy** [comment]
Celebrating a year+ of this issue in the Extended Sprints of Drupalcon Latinamerica 2015

**Comment by star-szr** [comment]
@develCuy - …patches (PRs) welcome?

**Comment by DevElCuy** [comment]
@Cottser, sure, any advice for a complete newbie on browser plug-ins? Note I do decent Javascript.

**Comment by star-szr** [comment]
@develCuy - sure, I can try to give a bit of direction :)

The code for the "insert image" plugin lives at https://github.com/dreditor/dreditor/blob/1.x/src/js/plugins/inline.image.js.

We already have some code that uses the cursor position so you may be able to "port" that into the insert image plugin. https://github.com/dreditor/dreditor/blob/1.x/src/js/plugins/issue.summary.template.js#L102

**Comment by sirtet** [comment]
I think this is a BUG, not an enhancement.
Currently, on Win7 Chrome 41 64bit, when i comment an issue and embed an uploaded image, it's added to the summary (body?), not to my comment. That definitely feels like a bug...

**Comment by kattekrab** [comment]
Yeah, I've been bumping up against this a lot recently.  Embed image is an AWESOME feature - but it always adds the image to the end of the Issue Summary, rather than the comment I'm writing.  Which confuses me every time.  Probably now I've actually written an issue about it, I'll remember, but if it is an easy one to fix, it would be an AWESOME thing to fix. :)  

Thanks though for everything about Dreditor - it's a seriously great tool.  Kudos. <3

**Comment by star-szr** [comment]
IMO the last two comments are a separate issue. I'll see if I can update Dreditor so that images go into comments again, if I come up with something I'll link the PR back here.

**Comment by star-szr** [comment]
https://github.com/dreditor/dreditor/pull/257

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#46
