### ISSUE TITLE
Support CKEditor for Review and Embed pastes

### ISSUE THREAD

**Issue by hestenet** [unicorn-fail/dreditor#283]
(Opening issues as I find them in testing the CKEditor d.o dev site: https://japerry-drupal.dev.devdrupal.org/node/2686207 - login info to test: Dries/test1234) 

After building from the current 2.x branch it looks like Dreditor paste features (from code review, or to embed images, for example) can't currently make it into the text area. 

These pastes do still work when switched into plain text view though.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729
