### ISSUE TITLE
HTML Structure Broken in Google Crome (Version 48.0.2564.116)

### ISSUE THREAD

**Issue by visabhishek** [unicorn-fail/dreditor#288]
Visit https://www.drupal.org/node/2752603

See screenshot 
![screenshot from 2016-06-23 22 07 02](https://cloud.githubusercontent.com/assets/2493261/16311744/573a554a-398f-11e6-983b-5e05ae049e05.png)

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729
