### ISSUE TITLE
interdiff file name suggestion button

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#29]
from: https://drupal.org/node/2068157

<em>Updated: Comment #0</em>

Related to [#2068151].

<h3 id="summary-problem-motivation">Problem/Motivation</h3>

Sometimes, interdiffs are made with filename interdiff.txt
This is hiding information about what it is the diff between,
and d.o has to calculate the number of other files called interdiff.txt and change the name to something like: interdiff_8682.txt

<h3 id="summary-proposed-resolution">Proposed resolution</h3>

Make an interdiff filename suggestion button, similar to [#1294662]

<h3 id="summary-remaining-tasks">Remaining tasks</h3>

<ul>
<li>Link to recommended interdiff</li>
<li>discuss what pattern to use</li>
<li>make patch</li>
</ul>

<h3 id="summary-ui-changes">User interface changes</h3>

Added button

<h3 id="summary-api-changes">API changes</h3>

No.

<h3 id="summary-related-issues">Related Issues</h3>

<ul>
<li>[#1294662]</li>
<li>[#2068151]</li>
</ul>

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#45
