### ISSUE TITLE
Page messed up by Dreditor

### ISSUE THREAD

**Issue by salvis** [unicorn-fail/dreditor#297]
I was asked to re-post here from https://github.com/dreditor/dreditor/issues/71:

The file table on the https://www.drupal.org/project/taxonomy_permissions/issues/2606040 page comes up completely garbled in the current Chrome/Win7 65.0.3325.146 (Official Build) (64-bit) and Dreditor 1.2.17. It looks fine in Firefox without Dreditor.

![image](https://user-images.githubusercontent.com/373828/37163227-8293a6ee-22f7-11e8-99da-0ff9c4731e5e.png)

**Comment by markhalliwell** [comment]
Unfortunately, this is just a side effect of the browser-based extension degrading over time due to markup changes on d.o. There are no plans to "fix" this as all browser-based extension development has ceased and effort has been focused on evolving this project into a separate library that will be included natively on d.o. See: https://www.drupal.org/project/drupalorg/issues/1673278#comment-11700291
