### ISSUE TITLE
Add Github-style word-level diff highlighting

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#30]
from https://drupal.org/node/1991148

Identifying partial line code changes in traditional diffs can be tedious and error-prone. A fix for a typo in code docs or a variable name in a long expression may require reviewers to carefully read an entire line to make sure they haven't overlooked differences. To help with this, some diff tools offer word-level highlighting. <code>git-diff</code> has the <code>--word-diff</code> option[1], for example, and Github has a very nice dual-highlighting implementation[2]. Similar functionality in Dreditor would be <em>super</em> helpful.

[1] <img src="http://drupal.org/files/git-word-diff.png" alt="git-word-diff.png" />
[2] <img src="http://drupal.org/files/github-word-diff.png" alt="github-word-diff.png" />

**Comment by markhalliwell** [comment]
Postponed on #161

**Comment by markhalliwell** [comment]
FWIW, this also requires the user to upload a patch using `git-diff` and the `--word-diff` option. So there may need to be a policy change on d.o for how we generate patches.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#44
