### ISSUE TITLE
Utilize d.o issue node/comment JSON info

### ISSUE THREAD

**Issue by helmo** [unicorn-fail/dreditor#55]
In https://github.com/dreditor/dreditor/issues/43 the use of issue json was temporarily removed. I'm adding this issue to track the todo that was added.

Another issue now also depends on this. https://github.com/dreditor/dreditor/issues/47

D.o issue that is blocking this: https://drupal.org/node/1710850

**Comment by markhalliwell** [comment]
This is no longer blocked: https://www.drupal.org/node/1710850#comment-9036533

Prefixing any node with `/api-d7` (as well as sending the appropriate `Accept: application/json` header) will result in JSON being returned.

**Comment by markhalliwell** [comment]
Official "API" handbook page: https://www.drupal.org/about-drupalorg/api

**Comment by clemens-tolboom** [comment]
API @ https://www.drupal.org/api

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#40
