### ISSUE TITLE
review patches before submission

### ISSUE THREAD

**Issue by disassembler** [unicorn-fail/dreditor#6]
It would be nice right after you upload the patch but before you save the issue, if a review tab appeared that allowed you to give your patch a last once-over before submitting it.

**Comment by star-szr** [comment]
I agree! Closed https://drupal.org/node/1948934 so we can track work on this feature here.

**Comment by wimleers** [comment]
Really? I think you should just do this on your computer. I always do a colorized git diff in the command line to review my patch before uploading it.

I do see the value of this for beginners though :)

**Comment by pcambra** [comment]
I suggested this in the first place because I force myself to doublecheck if the patch I'm uploading is the right one, reviewing just after attaching sounds helpful to me :)

**Comment by albertvolkman** [comment]
And, there's always the accidental patch mis-selection that I've done myself.

**Comment by wimleers** [comment]
@albertvolkman haha _that_ is _very_ true :D

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#53
