### ISSUE TITLE
[localize.d.o] Add button to create bug report for a context collision

### ISSUE THREAD

**Issue by podarok** [unicorn-fail/dreditor#68]
Due to https://drupal.org/node/2129315
Translators need create issue every time context collision found for some string
Good to get feature looks like button on localize.drupal.org for posting in new window issue for specified project with parameters via GET request 
Example 
https://drupal.org/node/add/project-issue/yandex_webmaster?version=7.x-2.x-dev&component=Code&category=2

All parameters are well known and accessible on translation page on localize.drupal.org

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#39
