### ISSUE TITLE
security.drupal.org

### ISSUE THREAD

**Issue by unn** [unicorn-fail/dreditor#75]
With the D7 upgrade of d.o there were probably a bunch of changes that were made to Dreditor. A bit ago, I noticed that Dreditor stopped working on security.drupal.org, probably as a result of the upgrade.

It'd be great, if support could be cobbled back together. I'm happy to help facilitate testing in any way.

**Comment by star-szr** [comment]
Hmm, would I be correct in thinking that security.drupal.org is still running D6? If so that would be a problem!

I'm not sure of a solution other than running two versions of Dreditor, one for https://drupal.org D7 and one for https://security.drupal.org D6.

**Comment by unn** [comment]
You would be correct, it's still D6. Thanks for the suggestion. What's a good version to use or maybe even commit to go back to?

**Comment by star-szr** [comment]
The last D6 tagged version is https://github.com/dreditor/dreditor/commits/1.1.7 and I believe the last D6 d.o compatible commit would be https://github.com/dreditor/dreditor/commit/f2f6123935d893e4f7604dfd2f8c9d264f948f66.

@markcarver should we remove https://github.com/dreditor/dreditor/blob/1.x/dreditor.user.js#L12 `@include *://*.drupal.org/*` so that Dreditor doesn't try to work on security.drupal.org (and other subdomains like qa.drupal.org)?

**Comment by markhalliwell** [comment]
Short answer: no. I do not want to try and support both versions of Drupal, it would be extremely time consuming.

My main suggestion would be to install both versions of Dreditor. Seeing how D6 and D7 handle Drupal.attachBehaviors differently, I don't think you should have any issues installing both. Dreditor 1.1.7 would work on D6 sites and Dreditor 1.2.0+ would work on D7 sites. Keep in mind though that any bugs in 1.1.7 wouldn't be fixed since the code moving forward would be for D7 sites.

The only other option would be to manually drag and drop a modified version of the user script 1.1.7 (`dreditor.user.js`) into your Chrome extensions window or manually alter your installed version of the Greasemonkey script in Firefox. You could even go as far as creating a separate profile if you felt that might help sandbox the different extensions properly.

Regardless, this is simply one of those things that, unfortunately, just happens. We could always just upgrade the https://security.drupal.org site to D7 :D

**Comment by klausi** [comment]
So can we fork the repository into "sdreditor", use the latest D6 code there and apply it to the security.drupal.org domain? So that people would have 2 user scripts installed, dreditor for D7 drupal.org and sdreditor for D6 security.drupal.org.

**Comment by markhalliwell** [comment]
> Web site developer/themer: We are currently redesigning security.drupal.org to help with our security issue workflows. If you are a developer and would like to work on improving the site, and the tools we use to manage security issues we have positions available for you.

I have just applied to be part of the security team to help with this. I will create a branch from the 1.1.7 code until this redesign process (which will hopefully be in D7) is complete.

**Comment by markhalliwell** [comment]
I created the branch, you can install the user script from:
https://github.com/dreditor/dreditor/raw/1.x-security/dreditor.user.js
