### ISSUE TITLE
Link issue numbers in a Project's Git Repository Viewer

### ISSUE THREAD

**Issue by gmclelland** [unicorn-fail/dreditor#85]
When viewing a project's git repo, I would like the issue numbers to be linked.

For example, on 
http://drupalcode.org/project/scald.git/commit/7ca918cb1c585e1ecbe1c7c0beb95a769bed8468

Issue #2097247 by tema: Added Make MEE available to all text fields by default.
#2097247 should be linked to the drupal issue.

It would help when reviewing commits.

What do you think?

**Comment by markhalliwell** [comment]
I don't think this is very plausible ATM, due to the fact that drupalcode.org is not a Drupal site (which Dreditor requires quite heavily). There are issues you can search for regarding either replacing this site with something better or fixing things like this. However, I do not think this should be a job for Dreditor.
