### ISSUE TITLE
add "make sticky" to issue summary text area

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#97]
Now that the issue edit fields are on the issue view again,

it would be really nice to have a "make sticky" on the summary text area. (It is already on the comment text area.)

**Comment by markhalliwell** [comment]
Should we make all text areas behave this way? @sun, thoughts?

**Comment by sun** [comment]
With the new issue/comment form, I noticed this, too.  But I'm not sure what the ideal solution is.  Here's how I interpret the possible _use-cases_:
1. When _commenting_ on an issue, the sticky comment field (only) is awesome, because you can scroll back to previous comments, in order to properly address every single one of them.  
   → The fact that only the comment field is sticky means that maximum vertical browser viewport space is available for the actual comments/content that you want to comment on.  Very helpful.
2. If you are @YesCT :+1: and you try to help to move an issue forward by updating its issue summary to properly reflect latest discussions, then it would be extraordinarily helpful if (just?) the issue summary field could be made sticky (disregarding other fields).  
   → Maximum space for reading comments + rewriting issue summary.
3. As a special case advancing on (2), what if you are attempting to rewrite the issue summary to properly reflect the current discussion/agreement/proposed solution, but you run into conceptual questions?  
   → Would it be helpful if you'd be able to prepare/formulate a comment while rewriting the issue summary?

Due to (1) and (2), I think it should be possible to make either the comment field or the summary field sticky (individually).

What I'm unsure about is (3).  If that use-case makes sense, then I wonder whether it would make sense to add a third _"Make sticky"_ button for the (entire) form?

@YesCT, since you are one of the primary consumers of the potential changes here, your insights and feedback on use-cases would be highly appreciated :-)  Please tell us what you want, we'll implement it. :)

**Comment by YesCT** [comment]
@sun :) 

I usually do both, update the issue summary and make a comment explaining what I have done. But I think I need the most detail (ability to scroll and update) when doing the issue summary.

I thinking making the issue summary sticky is my most used use case.
But I also can see making the whole form stick as helpful. Can we do all of them? have three "buttons"? comment sticky, summary sticky, whole form sticky? And play with it a bit to see which people find most useful?

**Comment by sun** [comment]
Alrighty, PR #104 performs the necessary adjustments.

Making the _entire_ issue update form sticky turned out to be funky — I had to adjust the "Unstick" (cancel) button to prevent it from possibly being located outside of the visible viewport, because the full form can be very large if all of the collapsible details are opened.

Whether that makes sense remains to be tested.  I assume you do not have a working development environment for Dreditor, so I guess we should simply merge that and try it out in production.
